{
    'name': 'Inventory Management',
    'version': '1.0',
    'description': "Inventory Management System for Australian Embassy",
    'summary': 'Australian Embassy',
    'author': 'Trusta Technologies',
    'website': 'trusta.co.id',
    'license': 'LGPL-3',
    'category': 'Services/InventoryManagement',
    'depends': [
        'base','uom','mail', 'user_login_status', 'auto_backup', 'auditlog'
    ],
    'data': [
        'security/ae_inventory_security.xml',
        'security/ir.model.access.csv',
        'views/ae_inventory.xml',
        'views/ae_inventory_master_group.xml',
        'views/ae_inventory_ledger_entries.xml',
        'views/ae_cutomer_list.xml',
        'views/ae_vendor.xml',
        'views/ae_agency_list.xml',
        'views/ae_location.xml',
	    'views/ae_master_subroom.xml',
        'views/ae_master_room.xml',
        'wizard/mainspreadsheets.xml',
        'wizard/storage_management.xml',
        'wizard/stationaryissued.xml',
        'wizard/settlingkit_inout.xml',
        'wizard/auctionreport.xml',
        'wizard/residential.xml',
        'wizard/journalsaleswizard.xml',
        'wizard/rollback_stationery_issued.xml',
        'wizard/residence_catalogue.xml',
        'wizard/updateSourcePrice.xml',
        'views/reports/reports.xml',
        'views/reports/mainspreadsheetdata.xml',
        'views/reports/stationeryissued.xml',
        'views/reports/settlingkits_inout.xml',
        'views/reports/auctionreport.xml',
        'views/reports/inventorydisposal.xml',
        'views/reports/settlingkit_disposal.xml',
        'views/reports/residential.xml',
        'views/reports/stationeryissued2.xml',
        'views/reports/auctionreports.xml',
        'views/reports/storagemanagement2.xml',
        'views/reports/residence_catalogue.xml',
        'views/ae_item_journal.xml',
        'views/ae_settling_kit.xml',
        'views/ae_auction.xml',
        'views/ae_user_logs.xml',
        'views/ae_settling_kit_mastergroup.xml',
        'views/ae_movement.xml',
        'views/ae_disposal.xml',
        'views/ae_user_login_logs.xml',
        'views/ae_inventory_scan_update.xml',
        'views/ae_update_logs.xml',
        'views/ae_stationery_issued_list.xml',
        'views/ae_login_logout.xml',
        'views/menu/inventory_menu.xml',
    ],
    'auto_install': False,
    'application': True,
    'installable': True,
    'assets': {
        'web.assets_backend': [
            'inventorymodule/static/src/js/*.js',
            'inventorymodule/static/src/css/*.css',
        ],
        'web.assets_frontend': [
            'inventorymodule/static/src/js/*.js',
            'inventorymodule/static/src/css/*.css',
        ],
        'web.assets_common': [
            'inventorymodule/static/src/js/*.js',
            'inventorymodule/static/src/css/*.css',
        ],
    'css': ['static/src/css/*.css'],
    },
    'images': ['static/description/inventoryicon.png'],
}